name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra ghostscript

      - name: render cv.pdf
        run: pdflatex cv.tex

      - name: render cv.png
        run: gs -sDEVICE=png16m -dSAFER -dBATCH -dNOPAUSE -r600 -sOutputFile=cv.png cv.pdf

      - name: Copy cv files to output
        run: mkdir output && cp cv.png output/cv.png && cp cv.pdf output/cv.pdf
        
      - name: Push to User Github Page
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "output"
          destination-github-username: "leorean"
          destination-repository-name: "leorean.github.io"
          user-email: leorean@hotmail.com
          target-branch: main
